services:
  index1:
    image: ghcr.io/pinecone-io/pinecone-index:latest
    platform: linux/amd64
    environment:
      PORT: 5081
      INDEX_TYPE: serverless
      DIMENSION: 512
      METRIC: cosine
    ports:
      - "5081:5081"
